cash: 7051.4
holdings:
- name: 恒生科技ETF
  symbol: sh513130
  cost: 0.7466
  shares: 4900.0
  strategy: value
  term: long
  track_index: H30533
  reason: 看好港股科技板块超跌后的估值修复，作为底仓配置
- name: 券商ETF
  symbol: sh512000
  cost: 0.595
  shares: 4800
  strategy: value
  term: mid
  track_index: '399975'
  reason: 博弈大盘反转及牛市旗手属性
- name: 南方纳指A
  symbol: '016452'
  type: otc_fund
  cost: 2.02
  shares: 118.81
  strategy: dca
  term: long
  reason: 纳指长线定投
- name: 华夏红利低波联接A
  symbol: 021482
  type: otc_fund
  cost: 1.0749
  shares: 1116.38
  strategy: dca
  term: mid
  reason: 底仓防御，获取稳定分红
